### ISSUE TITLE
Button Funnel/haus fehlt

### ISSUE THREAD

**Issue by johnnyblaze95** [pana87/getyour-platform#35]
Wenn ich mich als Anlagenbetreuber durch den Funnel klicke und alle Fragen zum ersten Thema "Haus" beantwortet habe, fehlt der speichern + weiter button.

Wunsch Nav Menü und speichern weiter Button

**Comment by pana87** [comment]
Auf abfrage haus gibt es doch einen speichern und weiter button

<img width="538" alt="Bildschirmfoto 2023-05-10 um 09 58 42" src="https://github.com/pana87/getyour-platform/assets/56303759/9b7906e0-d112-49df-aa90-6aa6b404936f">
