### ISSUE TITLE
Promoter-unternehmensdaten 

### ISSUE THREAD

**Issue by johnnyblaze95** [pana87/getyour-platform#36]
Wenn ich dort meine Websiten URL eingeben will, ist das miese action.

Wunsch: Ich denke wenn wir das einfach machen, würde es vielen besser gefallen. Beispiel: statt https://www.get-your.de/ geht auch get-your.de oder www.get-your.de, aber dass man sogar den letzten Slash eingeben muss, wird vermutlich viele irritieren und sie werden deshalb nicht weiter kommen und abbrechen müssen.

**Comment by pana87** [comment]
Der letzte Slash ist ein Sicherheitsfeature, damit keiner irgend eine Datei da reinschreiben kann und wir die dann automatisch verlinken. Wir verlinken auch nicht auf unsichere Seiten, deswegen brauchen wir das https:// Protokol. Das www vor der Domain kann man auch weg lassen.
