### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by johnnyblaze95** [pana87/getyour-platform#41]
auf der Landing Page (Startseite) wäre es richtig geil ein Blog erstellen zu können: 

Überschrift 
Text
Bild 
(später vllt ein Kommentar Feld + Daumen hoch/runter) 

Damit Content für die jeweiligen Plattformen erstellt werden kann.

**Comment by pana87** [comment]
Überschrift und Text funktioniert schon. Das Bild wird auch bald kommen. 👍
